dist: xenial
language: python
python:
  - 3.7
services:
  - xvfb

branches:
  except:
    - gh-pages

install:
  - npm i
script:
  - npm test

cache:
  npm: true
  pip: true
  directories:
  - node_modules
  - .cache/pip

deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: emiliano.heyns@iris-advies.com
  api_key:
    secure: a6XL8fBB/yRr4f5oZDbrMM9KpDF3uhwR0EJzzhJQByKyTpNIi1kw70/tAl1l0CPNhhMR6Q8qhXpykrb/z7/yCasu3DqkATMl9IUdTvZsWoP8a+I6QE0DiKtg65ycdYIDLcUTs1jloUJzCmEtHpkvB7iJeOItSrdUODuRbCNa4WMblkbAxslHAQxPqnWcBTG86fT7ot4ZmsXv6DqQCD/TWpiXKUWVzGKkDjYDMyrPfxNAsXu6KVFzofqxftNCIAJcVTzTp6Hi/vfQhHAAQdd6E6RnlAR55s57KUm3gWHMNY5gLs697AIGf/IJ8/K/6/r9OZHRBf99lrXP9eYTiCp587Nj1DZU5mr70woJMs6xHOX1tiF3yJQUkRWjxuvAPoD1pYunFznCtHxYmhzp/kOGugqLa3Y7O1rdjSftcPnTu0qK6kskgjXDvoEAxPHjfICf40dw/dsTYnTMRtmK088VFSnhiHJ66YzlQpvnxRM76Dlk4aGuQYDevdUUp1hNFBxf7ehUvFjaw7wDmQsdXgvYhPdNDV1MP4picBSmAudDpgK4Vuhk7ppuC01SBmYRyk8194mQ8ZB/HqtiZEVOhMi8Sq6el5tyV07S9h4ASJrksSbYIKQkfeUaA7AyMKVYDJfPRQL7GrzXrbkU6LQSvys+O1nKIt4vyddmhaRgq0G9oYE=
