name: test & publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
    - name: install dependencies
      run: |
        rm package-lock.json
        npm i
    - run: npm start
    - run: find dist -type f
    - name: Publish
      run: npm publish --provenance --access public
