name: test & publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1

    - name: install dependencies
      run: |
        npm ci --ignore-scripts
        shards install
    - run: npm test
    - name: Publish
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish --ignore-scripts
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
